server:
  port:8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.21.151.7:3307/lease
    username: root
    password: shijian1017.
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  jackson:
    time-zone: GMT+8
  data:
    redis:
      host: 10.21.151.7
      port: 6380
      database: 0
      password: shijian1017.

springdoc:
  default-flat-param-object: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1  # 已删除的标识为 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://10.21.151.7:9000
  access-key: minioadmin
  secret-key: shijian1017.
  bucket-name: lease